# auto-generated by init-project (harness submodule layout)
"""Delegates `python3 harness_cli.py <cmd>` to harness/harness_cli.py.
Auto-generated by `init-project`; do not edit manually.
Re-generate: python3 harness/harness_cli.py init-project --project . --overwrite
"""
import subprocess, sys
raise SystemExit(
    subprocess.run(
        [sys.executable, "harness/harness_cli.py", *sys.argv[1:]]
    ).returncode
)
